[tools]
# Languages & runtimes
zig = "latest"
go = "latest"
rust = "latest"
node = "lts"
deno = "latest"
bun = "latest"
pnpm = "latest"
yarn = "latest"
aube = "latest"
uv = "latest"
python = "3.13.3"
dotnet = "latest"

# Build tools
golangci-lint = "latest"
terraform = "latest"
sccache = "latest"
cargo-binstall = "latest"
tree-sitter = "latest"

# CLI tools
ghq = "latest"
lazygit = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"
yazi = "latest"
difftastic = "latest"
hyperfine = "latest"
1password = "latest"
fd = "latest"
jq = "latest"
"github:jftuga/less-Windows" = { version = "latest", exe = "less" }
fastfetch = "latest"
gh = "latest"
just = "latest"
kubectl = "latest"

# cargo packages
"cargo:cargo-outdated" = "latest"
"cargo:mergiraf" = "latest"

# npm packages
"npm:@antfu/ni" = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@sasazame/ccresume" = "latest"
"npm:ccusage" = "latest"
"npm:commitizen" = "latest"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
"npm:oxfmt" = "latest"
"npm:sdd-mcp" = "latest"
"npm:vde-layout" = "0.0.9"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
npm.package_manager = "bun"
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python", "node"]
