add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
$username\
$directory\
$git_branch\
$git_status\
$direnv\
$nix_shell\
$python\
$aws\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# Enable if it appears on the same line as the command
# right_format = """
# $cmd_duration\
# $time\
# """

# ----------------------------------------------------
# left module
# ----------------------------------------------------
[username]
show_always = true
format = "[ $user ]($style)"
style_user = 'bold fg:#7ebae4'
style_root = 'bold fg:#f38ba8'
[python]
format = """
[](fg:#7ebae4)\
[$virtualenv]($style)\
[](fg:#7ebae4)\
"""
style = "bold fg:#0a1828 bg:#7ebae4"

[fill]
symbol = '─'
[directory]
truncation_length = 6
truncation_symbol = ' '
truncate_to_repo = false
home_symbol = '~'
read_only = ' 󰌾 '
format = """
[](fg:#5277c3)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#5277c3)\
"""
style = 'bold fg:#e6eefb bg:#5277c3'
read_only_style = 'bold fg:#e6eefb bg:#5277c3'
[directory.substitutions]
"~/Project/github.com/" = " "
"Project/github.com/" = " "
"~/Project/github.com" = ""
"Project/github.com" = ""
"~/Project/gitlab.com/" = " "
"Project/gitlab.com/" = " "
"~/Project/gitlab.com" = ""
"Project/gitlab.com" = ""

[direnv]
disabled = false
format = """
[](fg:#5277c3)\
[$symbol$allowed]($style)\
[](fg:#5277c3)\
"""
style = "bold fg:#e6eefb bg:#5277c3"

[nix_shell]
disabled = false
symbol = " "
format = """
[](fg:#5277c3)\
[$symbol$state]($style)\
[](fg:#5277c3)\
"""
style = "bold fg:#e6eefb bg:#5277c3"

[git_branch]
symbol = ""
style = "fg:#0a1828 bg:#7ebae4"
format = """
[](fg:#7ebae4)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#0a1828 bg:#7ebae4"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#7ebae4)\
"""

# ----------------------------------------------------
# right module
# ----------------------------------------------------
[cmd_duration]
min_time = 1
style = 'fg:#5277c3'
format = "[ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time](fg:#7ebae4)]($style)'

# ----------------------------------------------------
# prompt module
# ----------------------------------------------------
[character]
vimcmd_symbol = '[V](bold green) '
