model = "gpt-5.6-terra"
model_reasoning_effort = "medium"
service_tier = "default"
default_permissions = "personal"

[windows]
sandbox = "elevated"

[tui]
theme = "monokai-extended-origin"
status_line = [
  "status",
  "project-name",
  "model-with-reasoning",
  "git-branch",
  "current-dir",
  "context-used",
]

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[permissions.personal]

[permissions.personal.filesystem]
":root" = "write"
glob_scan_max_depth = 16

[permissions.personal.filesystem.":workspace_roots"]
"**/.env" = "deny"
"**/.env.local" = "deny"
"**/.env.production" = "deny"
"**/.env.development" = "deny"
"**/credentials.json" = "deny"

[permissions.personal.network]
enabled = true

[projects."/home/t4ko/dotfiles"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/course-cli"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/zunoser/nakasyou-bakery-mod"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/vodai"]
trust_level = "trusted"

[projects."/home/t4ko/ダウンロード/アーカイブ"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/spotify-cli"]
trust_level = "trusted"

[projects."/home/t4ko/Project/Unity/amatousagi"]
trust_level = "trusted"

[projects."/home/t4ko"]
trust_level = "trusted"

[projects."/home/t4ko/Project/unity/amatousagi"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/cf-edgeNix"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/University-exams"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/cf-edgeNix"]
trust_level = "trusted"
