name: Setup Nix
description: Install Nix with the repository's trusted binary caches.

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@b4b293eae0b79aac8a161bb32925a5508c9cca93 # v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://nix.t4ko.pet https://vicinae.cachix.org https://cache.numtide.com https://codex-desktop-linux.cachix.org https://noctalia.cachix.org https://cache.nixos.org/
          trusted-public-keys = nix.t4ko.pet-1:0eRO18L1/5diWYWboKKPTejQGhGCHNITwELiUaX7Kps= vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g= codex-desktop-linux.cachix.org-1:nX/xy6AdK9hQE24A8ALGjkCKj2ObFmcnemiL5Cid4nk= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          accept-flake-config = true
