#!/usr/bin/env zsh

if ! command -v ghq >/dev/null 2>&1 || ! command -v fzf >/dev/null 2>&1; then
  zle -M 'ghq and fzf are required'
  return 1
fi

local src
src=$(ghq list | fzf --preview 'bat --color=always --style=header,grid --line-range :80 "$(ghq root)"/{}/README.* 2>/dev/null')
if [[ -n "$src" ]]; then
  BUFFER="cd $(ghq root)/$src"
  zle accept-line
fi
zle -R -c
