name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  nixos:
    name: NixOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build CI configuration
        run: nix build .#nixosConfigurations.nixos-ci.config.system.build.toplevel

  wsl:
    name: NixOS-WSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check WSL configuration
        run: bash scripts/check_wsl.sh
