add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$direnv\
$python\
$aws\
$fill\
$cmd_duration\
$time\
\n$character\
"""

[fill]
symbol = '─'
style = 'fg:#6c3483'

[directory]
truncation_length = 6
truncation_symbol = '.../'
truncate_to_repo = false
home_symbol = '~'
read_only = ' ro'
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold fg:#c778dd'
read_only_style = 'fg:#e06c75'

[git_branch]
symbol = ''
format = 'on [$symbol $branch]($style) '
style = 'fg:#b48ead'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:#e5c07b'

[direnv]
disabled = false
format = '[$symbol$allowed]($style) '
style = 'fg:#d19a66'

[python]
format = '[py $virtualenv]($style) '
style = 'fg:#e5c07b'

[cmd_duration]
min_time = 1
format = '[$duration]($style)'
style = 'fg:#6c3483'

[time]
disabled = false
time_format = '%R'
format = ' [$time]($style)'
style = 'fg:#b48ead'

[username]
show_always = true
format = '[$user]($style) in '
style_user = 'bold fg:#d19afc'
style_root = 'bold fg:#e06c75'

[character]
success_symbol = '[>>](bold fg:#c778dd)'
error_symbol = '[>>](bold fg:#e06c75)'
vimcmd_symbol = '[<<](bold fg:#98c379)'
