[tools]
# Languages & runtimes
node = "lts"
bun = "latest"
deno = "latest"
go = "latest"
pnpm = "latest"
uv = "latest"
zig = "latest"

# Build tools
golangci-lint = "latest"
terraform = "latest"
sccache = "latest"
cargo-binstall = "latest"
tree-sitter = "latest"

# npm packages
yarn = "latest"
"npm:@antfu/ni" = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@sasazame/ccresume" = "latest"
"npm:ccusage" = "latest"
"npm:commitizen" = "latest"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
"npm:oxfmt" = "latest"
"npm:sdd-mcp" = "latest"
"npm:vde-layout" = "0.0.9"
"npm:markdownlint-cli" = "latest"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
npm.package_manager = "bun"
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python", "node"]
